### ISSUE TITLE
Custom Fields - View Our Demo: Field type for link should be URL type, not Text.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Forest-Grove#2]
![image](https://cloud.githubusercontent.com/assets/12888048/15879711/2460e392-2d59-11e6-849f-3d3042b6ef96.png)
![image](https://cloud.githubusercontent.com/assets/12888048/15879717/33199eba-2d59-11e6-8e43-3e6a0383069d.png)

**Comment by Louienator** [comment]
I've just made the entire Field as text and made all as a pop-up fancy-box except for the solutions single page..

**Comment by romatitan** [comment]
@Louienator 
You should clarify this issue #11 first before implementing the functionality of all "View Demo" button (opening a form in a fancy box or links to an external link.)

Please note that in this issue, you already set the field as URL type and your comment seems to be "unfit" to the thread.
![image](https://cloud.githubusercontent.com/assets/12888048/16578909/a5e18954-42cf-11e6-9538-fd2a6bb69324.png)
