### ISSUE TITLE
It seems that the Testimonials and Clients page is the same based on the old design. Only the page title was changed

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Forest-Grove#79]
Should we create pages for Testimonials and Clients or just one?

![image](https://cloud.githubusercontent.com/assets/12888048/15923705/179f7322-2e61-11e6-8874-2de32da13d15.png)
![image](https://cloud.githubusercontent.com/assets/12888048/15923746/3e1513e0-2e61-11e6-9457-146b5d7ba52f.png)

**Comment by Louienator** [comment]
Just igonre the "client" page

**Comment by romatitan** [comment]
How come this is an invalid?
This is a question that needs clarification.
